### ISSUE TITLE
Which events are being fired when an ad is paused due to loading difficulties?

### ISSUE THREAD

**Issue by BranoMatan** [MailOnline/VPAIDHTML5Client#8]
When an ad starts but not completely loaded, sometimes the ad's progress time reach the end of the loaded time. I want to have an indication for that, because it is important for me to know when an ad paused.
I know the AdPaused event is fired when the user intentionally pause the ad, but is there an event that is being fired when the ad is paused due to other difficulties?
If there is not, is it possible to add an event like that?

**Comment by Fetz** [comment]
Looking at the spec:
http://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf
3.3 Dispatched Events...

I don't see any event from VPAID that would give that...

What you can use is the `getAdRemainingTime()` to see if the time is progressing or not:

from the documentation:
"If the property is not implemented, the ad unit returns a value of -1. A value of -2 is returned
when time remaining is unknown. Unknown remaining time usually indicates that a user is
actively engaged with the ad."

**Comment by BranoMatan** [comment]
Thanks for the response.
I have implemented something similar to what you suggested.
