### ISSUE TITLE
running post-roll ads VPAIDHTML5Client

### ISSUE THREAD

**Issue by deepak22595** [MailOnline/VPAIDHTML5Client#9]
I want to run pre-roll and post-roll ads. 
How can i do that with VPAIDHTML5Client.?
Where can i find the list of options "vpaidOptions" that can be used with VPAIDHTML5Client(el, video, templateConfig, vpaidOptions).

**Comment by Fetz** [comment]
The VPAIDHTML5Client doesn't care about pre-roll or post-roll at all, it only helps to handle with the loading, and events of VPAID ad. If you want a solution more complete please see:

https://github.com/MailOnline/videojs-vast-vpaid

Regarding the second question:

vpaidOptions for now only supports for now timeout

**Comment by deepak22595** [comment]
Thanks a lot.
